In [1]:
import torch

x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
x = torch.arange(1, 10 + 1)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
x = torch.arange(1, 10 + 1, 2)
x

tensor([1, 3, 5, 7, 9])