In [6]:
import torch

x = torch.randperm(10)
x

tensor([0, 4, 9, 2, 3, 5, 8, 7, 1, 6])

In [7]:
x = torch.argsort(x)
x

tensor([0, 8, 3, 4, 1, 5, 9, 7, 6, 2])

In [ ]:
x = torch.randperm(16).reshape(4, 4)
x

tensor([[ 9,  4, 16,  8, 19],
        [ 3,  2, 13,  7, 17],
        [18,  5,  0, 12, 14],
        [ 1, 11, 10,  6, 15]])

In [9]:
torch.argsort(x, dim=0)  # sorts along dim 0

tensor([[3, 1, 2, 3, 2],
        [1, 0, 3, 1, 3],
        [0, 2, 1, 0, 1],
        [2, 3, 0, 2, 0]])

In [10]:
torch.argsort(x, dim=1)  # sorts along dim 1

tensor([[1, 3, 0, 2, 4],
        [1, 0, 3, 2, 4],
        [2, 1, 3, 4, 0],
        [0, 3, 2, 1, 4]])