In [1]:
import torch

x = torch.randint(1, 10 + 1, (2,))
x

tensor([7, 9])

In [2]:
x = torch.randint(1, 10 + 1, (2, 2))
x

tensor([[3, 9],
        [3, 6]])

In [3]:
x = torch.randint(1, 10 + 1, (2, 2, 2))
x

tensor([[[ 8, 10],
         [ 2,  5]],

        [[ 4,  4],
         [ 7,  5]]])