In [ ]:
import torch

x = torch.arange(1, 12 + 1)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [2]:
x = torch.reshape(x, (2, 6))
x

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [3]:
x = torch.reshape(x, (3, 2, 2))
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [4]:
x = torch.reshape(x, (4, 3))
x

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])